apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
  labels:
    app: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: supermario
        # image: 328863170107.dkr.ecr.us-east-1.amazonaws.com/supermario:latest
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: supermario-service
spec:
  selector:
    app: supermario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


# https://redhat-scholars.github.io/argocd-tutorial/argocd-tutorial/02-getting_started.html
# https://github.com/argoproj/argo-cd/blob/master/docs/getting_started.md